import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const specPath = path.join(repositoryRoot, 'spec/yuque-openapi.yaml');
const outputPath = path.join(repositoryRoot, 'src/client/types.gen.ts');
const checkOnly = process.argv.includes('--check');

const header = `/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT.
 * Edit spec/yuque-openapi.yaml and run \`npm run gen:types\`.
 * Generated by openapi-typescript.
 */

`;

async function generateTypes() {
  const ast = await openapiTS(pathToFileURL(specPath), {
    rootTypes: true,
    rootTypesKeepCasing: true,
    rootTypesNoSchemaPrefix: true,
    silent: true,
  });

  return `${header}${astToString(ast)}`;
}

const generated = await generateTypes();

if (!checkOnly) {
  await writeFile(outputPath, generated);
  console.log(`Generated ${path.relative(repositoryRoot, outputPath)}`);
} else {
  const temporaryDirectory = await mkdtemp(path.join(tmpdir(), 'yuque-open-cli-types-'));
  const temporaryOutput = path.join(temporaryDirectory, 'types.gen.ts');

  try {
    await writeFile(temporaryOutput, generated);

    let committed;
    try {
      committed = await readFile(outputPath, 'utf8');
    } catch (error) {
      if (error?.code !== 'ENOENT') {
        throw error;
      }
    }

    if (committed !== (await readFile(temporaryOutput, 'utf8'))) {
      console.error(
        'Generated OpenAPI types are out of date. Run `npm run gen:types` and commit src/client/types.gen.ts.'
      );
      process.exitCode = 1;
    } else {
      console.log('Generated OpenAPI types are up to date.');
    }
  } finally {
    await rm(temporaryDirectory, { recursive: true });
  }
}
